export const providers = [
  'OpenAI',
  'Anthropic',
  'Google',
  'Meta',
  'Cohere',
  'AI21 Labs',
  'Aleph Alpha',
  'Hugging Face',
  'Stability AI',
  'Midjourney',
  'DeepSeek',
  'Mistral AI',
  'Technology Innovation Institute',
  'EleutherAI',
  'NVIDIA',
  'Databricks',
  'Replicate',
  'Together AI',
  'Mosaic',
  'Perplexity',
  'Runaway',
  'Inflection AI',
  'Adept',
  'Salesforce',
  'Reka',
  'Groq',
  '01.AI',
  'Alibaba',
  'Baichuan',
  'RWKV',
  'Cerebras',
  'BigScience',
  'Colossal AI',
  'Jina AI',
  'Nomic AI',
  'Voyage AI',
  'Moonshot AI',
  'Zhipu AI',
  'Amazon',
  'Microsoft',
  'IBM',
  'Apple',
  'Samsung',
  'Baidu',
  'Tencent',
  'ByteDance',
  'Yandex',
  'Naver',
  'Kakao',
  'Line',
  'SenseTime',
  'Megvii',
  'CloudMinds',
  'UBTech',
  'iFlytek',
  'Horizon Robotics',
  'Preferred Networks',
  'DeepMind',
  'Allen Institute for AI',
  'Stanford HAI',
  'MIT CSAIL',
  'Berkeley AI Research',
  'Carnegie Mellon University',
  'University of Toronto',
  'University of Washington',
  'University of Cambridge',
  'University of Oxford',
  'ETH Zurich',
  'Max Planck Institute',
  'INRIA',
  'MILA',
  'Vector Institute',
  'IDSIA',
  'NNAISENSE',
  'Vicarious',
  'Numenta',
  'Cogitai',
  'Petuum',
  'H2O.ai',
  'DataRobot',
  'C3.ai',
  'Scale AI',
  'Weights & Biases',
  'Determined AI',
  'Snorkel AI',
  'Primer',
  'Arize AI',
  'Arthur',
  'Fiddler',
  'TruEra',
  'WhyLabs',
  'Robust Intelligence',
  'Tecton',
  'Featureform',
  'Feast',
  'Hopsworks',
  'Domino Data Lab',
  'Dataiku',
  'Databricks',
  'Snowflake',
  'Dremio',
  'Starburst',
  'Firebolt',
  'Imply',
  'Preset',
  'Mode',
  'Hex',
  'Observable',
  'Deepnote',
  'Noteable',
  'Posit',
  'Anaconda',
  'Gradient',
  'Paperspace',
  'Lambda Labs',
  'CoreWeave',
  'RunPod',
  'Vast.ai',
  'Genesis Cloud',
  'Coreweave',
  'Modal',
  'Anyscale',
  'Baseten',
  'Banana',
  'Modelz',
  'Beam',
  'Vercel',
  'Netlify',
  'Cloudflare',
  'Fastly',
  'Akamai',
  'Limelight',
  'StackPath',
  'Edgio',
  'Fly.io',
  'Railway',
  'Render',
  'Heroku',
  'DigitalOcean',
  'Linode',
  'Vultr',
  'OVH',
  'Hetzner',
  'AWS',
  'Azure',
  'GCP',
  'IBM Cloud',
  'Oracle Cloud',
  'Alibaba Cloud',
  'Tencent Cloud',
  'Huawei Cloud',
  'Baidu Cloud',
  'Naver Cloud',
  'Kakao Cloud',
  'NTT',
  'Fujitsu',
  'Hitachi',
  'NEC',
  'Ericsson',
  'Nokia',
  'Huawei',
  'ZTE',
  'Cisco',
  'Juniper',
  'Arista',
  'Palo Alto Networks',
  'Fortinet',
  'Check Point',
  'Zscaler',
  'Cloudflare',
  'Akamai',
  'Fastly',
  'Imperva',
  'F5',
  'Barracuda',
  'SonicWall',
  'WatchGuard',
  'Sophos',
  'McAfee',
  'Symantec',
  'Trend Micro',
  'Kaspersky',
  'ESET',
  'Bitdefender',
  'Malwarebytes',
  'CrowdStrike',
  'SentinelOne',
  'Carbon Black',
  'Cylance',
  'Darktrace',
  'Vectra',
  'ExtraHop',
  'Corelight',
  'Recorded Future',
  'Mandiant',
  'CyberArk',
  'Okta',
  'Ping Identity',
  'ForgeRock',
  'Auth0',
  'OneLogin',
  'Duo Security',
  'RSA Security',
  'Yubico',
  'HackerOne',
  'Bugcrowd',
  'Synack',
  'Cobalt',
  'Detectify',
  'PortSwigger',
  'Snyk',
  'Veracode',
  'Checkmarx',
  'WhiteSource',
  'Sonatype',
  'Aqua Security',
  'Lacework',
  'Wiz',
  'Orca Security',
  'Prisma Cloud',
  'Datadog',
  'New Relic',
  'Dynatrace',
  'AppDynamics',
  'Splunk',
  'Elastic',
  'Sumo Logic',
  'LogDNA',
  'Grafana',
  'Prometheus',
  'InfluxData',
  'Chronosphere',
  'Honeycomb',
  'Lightstep',
  'Sentry',
  'PagerDuty',
  'OpsGenie',
  'VictorOps',
  'xMatters',
  'ServiceNow',
  'Atlassian',
  'GitLab',
  'GitHub',
  'Bitbucket',
  'CircleCI',
  'Jenkins',
  'Travis CI',
  'TeamCity',
  'Bamboo',
  'GoCD',
  'Spinnaker',
  'Harness',
  'Armory',
  'Argo',
  'Flux',
  'Flagger',
  'Istio',
  'Linkerd',
  'Consul',
  'Envoy',
  'NGINX',
  'HAProxy',
  'Traefik',
  'Kong',
  'Tyk',
  'Ambassador',
  'Gloo',
  'Contour',
  'Cilium',
  'Calico',
  'Weave',
  'Anthos',
  'OpenShift',
  'Rancher',
  'Tanzu',
  'Platform9',
  'D2iQ',
  'Mirantis',
  'SUSE',
  'Red Hat',
  'Canonical',
  'VMware',
  'Nutanix',
  'Citrix',
  'Parallels',
  'QEMU',
  'VirtualBox',
  'Xen',
  'KVM',
  'Hyper-V',
  'Docker',
  'Podman',
  'containerd',
  'CRI-O',
  'Kubernetes',
  'Nomad',
  'Mesos',
  'Swarm',
  'Terraform',
  'Pulumi',
  'CloudFormation',
  'Ansible',
  'Chef',
  'Puppet',
  'SaltStack',
  'Vagrant',
  'Packer',
  'Crossplane',
  'OpenTofu',
  'CDK',
  'Serverless Framework',
  'SAM',
  'Chalice',
  'Zappa',
  'Claudia.js',
  'Architect',
  'Vercel',
  'Netlify',
  'Cloudflare Workers',
  'Fastly Compute',
  'Deno Deploy',
  'Fly.io',
  'Railway',
  'Render',
  'Heroku',
  'DigitalOcean App Platform',
  'Google App Engine',
  'AWS Elastic Beanstalk',
  'Azure App Service',
  'IBM Cloud Foundry',
  'Pivotal Cloud Foundry',
  'Dokku',
  'Aptible',
  'Convox',
  'Flynn',
  'Koyeb',
  'Qovery',
  'Porter',
  'Coolify',
  'Caprover',
  'Northflank',
  'Coherence',
  'Encore',
  'Ampt',
  'Shuttle',
  'Zeabur',
  'Napkin',
  'Hop',
  'Adaptable',
  'Replit',
  'Glitch',
  'CodeSandbox',
  'StackBlitz',
  'Gitpod',
  'GitHub Codespaces',
  'AWS Cloud9',
  'Google Cloud Shell',
  'Azure Cloud Shell',
  'Coder',
  'Eclipse Che',
  'Theia',
  'VSCode',
  'Neovim',
  'Emacs',
  'Vim',
  'Sublime Text',
  'Atom',
  'Brackets',
  'Light Table',
  'JetBrains',
  'Eclipse',
  'NetBeans',
  'Xcode',
  'Android Studio',
  'Visual Studio',
  'Code::Blocks',
  'Qt Creator',
  'KDevelop',
  'CLion',
  'PyCharm',
  'IntelliJ IDEA',
  'WebStorm',
  'PhpStorm',
  'RubyMine',
  'GoLand',
  'Rider',
  'DataGrip',
  'DataSpell',
  'Fleet',
  'Cursor',
  'Zed',
  'Lapce',
  'Helix',
  'Kakoune',
  'Amp',
  'Xi',
  'Onivim',
  'Nova',
  'BBEdit',
  'TextMate',
  'UltraEdit',
  'EditPlus',
  'Notepad++',
  'Geany',
  'Gedit',
  'Kate',
  'Kwrite',
  'Mousepad',
  'Leafpad',
  'Nano',
  'Pico',
  'Joe',
  'Jed',
  'Micro',
  'Moe',
  'Ne',
  'Jove',
  'Zile',
  'Mg',
  'Vile',
  'Elvis',
  'Nvi',
  'Ex',
  'Ed',
  'Sam',
  'Acme',
  'Wily',
  'Edwood',
  'Structural',
  'Anthropic',
  'Cohere',
  'AI21 Labs',
  'Aleph Alpha',
  'Hugging Face',
  'Stability AI',
  'Midjourney',
  'DeepSeek',
  'Mistral AI',
  'Technology Innovation Institute',
  'EleutherAI',
  'NVIDIA',
  'Databricks',
  'Replicate',
  'Together AI',
  'Mosaic',
  'Perplexity',
  'Runaway',
  'Inflection AI',
  'Adept',
  'Salesforce',
  'Reka',
  'Groq',
  '01.AI',
  'Alibaba',
  'Baichuan',
  'RWKV',
  'Cerebras',
  'BigScience',
  'Colossal AI',
  'Jina AI',
  'Nomic AI',
  'Voyage AI',
  'Moonshot AI',
  'Zhipu AI'
]

export function getProviderName(provider: string): string {
  switch (provider) {
    case 'openai':
      return 'OpenAI'
    case 'anthropic':
      return 'Anthropic'
    case 'google':
      return 'Google AI Studio'
    case 'vertex':
      return 'Google'
    case 'meta':
      return 'Meta'
    case 'mistral':
      return 'Mistral AI'
    case 'cohere':
      return 'Cohere'
    case 'stability':
      return 'Stability AI'
    case 'deepseek':
      return 'DeepSeek'
    case 'ai21':
      return 'AI21 Labs'
    case 'alephalpha':
      return 'Aleph Alpha'
    case 'huggingface':
      return 'Hugging Face'
    case 'tii':
      return 'Technology Innovation Institute'
    case 'eleutherai':
      return 'EleutherAI'
    case 'nvidia':
      return 'NVIDIA'
    case 'databricks':
      return 'Databricks'
    case 'replicate':
      return 'Replicate'
    case 'together':
      return 'Together AI'
    case 'mosaic':
      return 'Mosaic'
    case 'perplexity':
      return 'Perplexity'
    case 'runaway':
      return 'Runaway'
    case 'inflection':
      return 'Inflection AI'
    case 'adept':
      return 'Adept'
    case 'salesforce':
      return 'Salesforce'
    case 'reka':
      return 'Reka'
    case 'groq':
      return 'Groq'
    case '01ai':
      return '01.AI'
    case 'alibaba':
      return 'Alibaba'
    case 'baichuan':
      return 'Baichuan'
    case 'rwkv':
      return 'RWKV'
    case 'cerebras':
      return 'Cerebras'
    case 'bigscience':
      return 'BigScience'
    case 'colossalai':
      return 'Colossal AI'
    case 'jina':
      return 'Jina AI'
    case 'nomic':
      return 'Nomic AI'
    case 'voyage':
      return 'Voyage AI'
    case 'moonshot':
      return 'Moonshot AI'
    case 'zhipu':
      return 'Zhipu AI'
    default:
      return provider
        .replace(/([A-Z])/g, ' $1')
        .replace(/^./, (str) => str.toUpperCase())
        .trim()
  }
}
